MODULE_LINT=/usr/share/moduleframework/tools/modulelint.py
CMD=python -m avocado run --filter-by-tags=-WIP $(MODULE_LINT) 
#CMD=python -m avocado run --filter-by-tags=-WIP

test1:
	$(CMD) SanityTest1.py
